language: ruby
before_install:
  - gem install bundler
  - bundle --version
rvm:
  - 2.1.0-p0
  - 2.1.8
  - 2.2.0-p0
  - 2.2.4
  - 2.3.0
  - rbx-2
  - jruby-9.0.5.0
matrix:
  allow_failures:
    - rvm: rbx-2
