language: ruby
before_install:
  - gem update --system
  - gem install bundler
  - bundle --version
rvm:
  - 2.1.0-p0
  - 2.1.10
  - 2.2.0-p0
  - 2.2.6
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - jruby-9.1.6.0
