language: ruby
env:
  - VERAPDF_VERSION=1.6.3
  - VERAPDF_VERSION_SHORT=1.6
before_install:
  - gem update --system
  - gem install bundler
  - bundle --version
  - wget http://software.verapdf.org/rel/${VERAPDF_VERSION_SHORT}/verapdf-${VERAPDF_VERSION}-installer.zip
  - unzip verapdf-${VERAPDF_VERSION}-installer.zip
  - java -jar -DINSTALL_PATH=${PWD}/verapdf verapdf-${VERAPDF_VERSION}/verapdf-izpack-installer-${VERAPDF_VERSION}.jar -options-system
  - export PATH=$PATH:$PWD/verapdf
  - verapdf --version
rvm:
  - 2.1.0-p0
  - 2.1.10
  - 2.2.0-p0
  - 2.2.6
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - jruby-9.1.7.0
