language: ruby
before_install:
  - gem install bundler
  - bundle --version
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
matrix:
  include:
    - rvm: jruby-1.7.22
      env: JRUBY_ORTS=--2.0
  allow_failures:
    - rvm: rbx-2
