language: ruby
before_install:
  - gem install bundler
  - bundle --version
rvm:
  - 2.0.0-p0
  - 2.0.0-p648
  - 2.1.0-p0
  - 2.1.8
  - 2.2.0-p0
  - 2.2.4
  - rbx-2
  - jruby-9.0.4.0
matrix:
  include:
    - rvm: jruby-1.7.22
      env: JRUBY_ORTS=--2.0
  allow_failures:
    - rvm: rbx-2
